apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-api-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://github.com/OWNER/kubernetes-platform-gitops.git
      targetRevision: HEAD
      path: helm/platform-api
      helm:
        releaseName: platform-api
        valueFiles:
          - $values/argocd/envs/dev/values.yaml
    - repoURL: https://github.com/OWNER/kubernetes-platform-gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
