{{- if not .Values.argoRollouts.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform-api.fullname" . }}
  labels:
    {{- include "platform-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.updateStrategy.maxSurge }}
      maxUnavailable: {{ .Values.updateStrategy.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "platform-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "platform-api.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "platform-api.podSpec" . | nindent 6 }}
{{- end }}
