{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platform-api.serviceAccountName" . }}
  labels:
    {{- include "platform-api.labels" . | nindent 4 }}
  {{- $annotations := deepCopy (.Values.serviceAccount.annotations | default dict) }}
  {{- if and .Values.serviceAccount.roleArn (not (hasKey $annotations "eks.amazonaws.com/role-arn")) }}
  {{- $_ := set $annotations "eks.amazonaws.com/role-arn" .Values.serviceAccount.roleArn }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
